import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <nav style={{
          background: 'rgba(0,0,0,0.3)',
          padding: '1rem 2rem',
          borderBottom: '1px solid rgba(255,255,255,0.1)',
          display: 'flex',
          gap: '2rem'
        }}>
          <a href="/" style={{ color: 'white', textDecoration: 'none', fontWeight: 'bold' }}>
            Dashboard
          </a>
          <a href="/picks" style={{ color: 'white', textDecoration: 'none' }}>
            All Picks
          </a>
          <a href="/stats" style={{ color: 'white', textDecoration: 'none' }}>
            Stats
          </a>
        </nav>
        {children}
      </body>
    </html>
  )
}
